services:
  ttlab-website:
    build:
      context: .
      network: host
    container_name: ttlab-website
    ports:
      - "127.0.0.1:3000:3000" # chỉ Nginx trên host truy cập được
    environment:
      - NODE_ENV=production
    # ADMIN_PASSWORD, SESSION_SECRET
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
    restart: unless-stopped
